{
 "title": "MAAS STATS",
 "time": { "from": "now", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "MAAS Cluster",
   "type": "stat",
   "gridPos": { "h": 19, "w": 16, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "maas_machine_power_state", "legendFormat": "{{power}}:{{hostname}}" }
   ]
  },
  {
   "title": "Region RAM Free",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes * 100)/ 1024",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "SGG01.U3.001 RH",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tunnel_humidity_percent", "legendFormat": "Humidity" }
   ]
  },
  {
   "title": "SGG01.U3.001 Tunnel ºC",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tunnel_temperature_celsius", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "NAS ºC",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diskTemperature{job=\"nas_snmp_exporter\"}",
     "legendFormat": "{{path}}: {{status}}"
    }
   ]
  },
  {
   "title": "NAS Disk Status",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "diskStatus{instance=\"10.34.64.230\"}",
     "legendFormat": "{{diskID}}"
    }
   ]
  },
  {
   "title": "NAS Mem Free",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrStorageUsed{hrStorageDescr=\"/volume1\"}",
     "legendFormat": "Volume 1"
    }
   ]
  },
  {
   "title": "Failed Machines",
   "type": "table",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "maas_machine_power_state{status_message=\"Failed to query node's BMC - Request failed with response status code: 503.\"} or maas_machine_power_state{status_message=\"Failed to query node's BMC - Connection was refused by other side: Connection was refused by other side: 111: Connection refused..\"} or maas_machine_power_state{status_message=\"Failed to query node's BMC - An error occurred while connecting: An error occurred while connecting: 113: No route to host..\"} or maas_machine_power_state{status_message=\"Failed to power on node - Power on for the node failed: Failed talking to node's BMC: Failed to power safe6e. BMC never transitioned from off to on.\"} ",
     "legendFormat": "{{status_message}}"
    }
   ]
  },
  {
   "title": "Failed Memmory Test",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 21 },
   "targets": [
    {
     "expr": "maas_machine_status{storage_test_status_name=\"Failed\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}